### ISSUE TITLE
Licens för projektet

### ISSUE THREAD

**Issue by simongottschlag** [DennizSvens/teams-app-eid#12]
Hej!

Fantastiskt fint projekt ni skapat. Grymt jobbat! :1st_place_medal: 

Jag såg att det står [`ISC`](https://en.wikipedia.org/wiki/ISC_license) i [`package.json`](https://github.com/DennizSvens/teams-app-eid/blob/836f5b78c4b969672f8a55952ee0e25a7aad44e0/package.json#L14) kring licens, men inget mer. 

Skulle det finnas möjlighet att lägga upp lite information kring licens i repot? Viktigt för vår del att veta vilken licens som gäller innan vi använder något.

Keep up the great work!

**Comment by DSorlov** [comment]
Fixat https://github.com/DennizSvens/teams-app-eid/commit/e7fb2312e052b3a8584d3bdb416ffbe4b69eacdb
